export class User{
    Id?:number;
    UserName:string;
    FirstName:string;
    LastName:string;
    Password:string;
    Email:string;
    Phone:string;
    BirthDate:Date;
    LastLogin:Date;
    IsActive:boolean;
    IsAdmin:boolean;
    Confirmed:boolean;
    BuyingTimes:number;
    BuyingValue:number;
    constructor(UserName:string,
        FirstName:string,
        LastName:string,
        Password:string,
        Email:string,
        Phone:string,
        BirthDate:Date,
        LastLogin:Date,
        IsActive:boolean,
        IsAdmin:boolean,
        Confirmed:boolean,
        BuyingTimes:number,
        BuyingValue:number){
        this.UserName=UserName;
        this.FirstName=FirstName;
        this.LastLogin=LastLogin;
        this.LastName=LastName;
        this.IsActive=IsActive;
        this.IsAdmin=IsAdmin;
        this.BirthDate=BirthDate;
        this.BuyingTimes=BuyingTimes;
        this.BuyingValue=BuyingValue;
        this.Email=Email;
        this.Password=Password;
        this.Phone=Phone;
        this.Confirmed=Confirmed;
    }
}